Added online boutique changes

diff --git a/benchmarks/online-boutique/kubernetes-manifests-jaeger.yaml b/benchmarks/online-boutique/kubernetes-manifests-jaeger.yaml
--- a/benchmarks/online-boutique/kubernetes-manifests-jaeger.yaml
+++ b/benchmarks/online-boutique/kubernetes-manifests-jaeger.yaml
@@ -54,7 +54,7 @@ spec:
         - name: PORT
           value: "8080"
         - name: DISABLE_TRACING
-          value: "1"
+          value: "0"
         - name: DISABLE_PROFILER
           value: "1"
         readinessProbe:
@@ -141,11 +141,11 @@ spec:
           - name: DISABLE_STATS
             value: "1"
           - name: DISABLE_TRACING
-            value: "1"
+            value: "0"
           - name: DISABLE_PROFILER
             value: "1"
-          # - name: JAEGER_SERVICE_ADDR
-          #   value: "jaeger-collector:14268"
+          - name: JAEGER_SERVICE_ADDR
+            value: "jaeger-collector:14268"
           resources:
             requests:
               cpu: 100m
@@ -213,11 +213,13 @@ spec:
         - name: PRODUCT_CATALOG_SERVICE_ADDR
           value: "productcatalogservice:3550"
         - name: DISABLE_TRACING
-          value: "1"
+          value: "0"
         - name: DISABLE_PROFILER
           value: "1"
         - name: DISABLE_DEBUGGER
           value: "1"
+        - name: JAEGER_SERVICE_ADDR
+          value: "jaeger-collector:14268"
         resources:
           requests:
             cpu: 100m
@@ -310,11 +312,11 @@ spec:
           # - name: ENV_PLATFORM 
           #   value: "aws"
           - name: DISABLE_TRACING
-            value: "1"
+            value: "0"
           - name: DISABLE_PROFILER
             value: "1"
-          # - name: JAEGER_SERVICE_ADDR
-          #   value: "jaeger-collector:14268"
+          - name: JAEGER_SERVICE_ADDR
+            value: "jaeger-collector:14268"
           # - name: CYMBAL_BRANDING
           #   value: "true"
           resources:
@@ -387,11 +389,13 @@ spec:
         - name: PORT
           value: "50051"
         - name: DISABLE_TRACING
-          value: "1"
+          value: "0"
         - name: DISABLE_PROFILER
           value: "1"
         - name: DISABLE_DEBUGGER
           value: "1"
+        - name: JAEGER_SERVICE_ADDR
+          value: "jaeger-collector:14268"
         readinessProbe:
           exec:
             command: ["/bin/grpc_health_probe", "-addr=:50051"]
@@ -457,11 +461,11 @@ spec:
         - name: DISABLE_STATS
           value: "1"
         - name: DISABLE_TRACING
-          value: "1"
+          value: "0"
         - name: DISABLE_PROFILER
           value: "1"
-        # - name: JAEGER_SERVICE_ADDR
-        #   value: "jaeger-collector:14268"
+        - name: JAEGER_SERVICE_ADDR
+          value: "jaeger-collector:14268"
         readinessProbe:
           exec:
             command: ["/bin/grpc_health_probe", "-addr=:3550"]
@@ -553,69 +557,71 @@ spec:
   - name: grpc
     port: 7070
     targetPort: 7070
----
-apiVersion: apps/v1
-kind: Deployment
-metadata:
-  name: loadgenerator
-spec:
-  selector:
-    matchLabels:
-      app: loadgenerator
-  replicas: 1
-  template:
-    metadata:
-      labels:
-        app: loadgenerator
-      annotations:
-        sidecar.istio.io/rewriteAppHTTPProbers: "true"
-    spec:
-      serviceAccountName: default
-      terminationGracePeriodSeconds: 5
-      restartPolicy: Always
-      securityContext:
-        fsGroup: 1000
-        runAsGroup: 1000
-        runAsNonRoot: true
-        runAsUser: 1000
-      initContainers:
-      - command:
-        - /bin/sh
-        - -exc
-        - |
-          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
-          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
-          if test $STATUSCODE -ne 200; then
-              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
-              exit 1
-          fi
-        name: frontend-check
-        image: busybox:latest
-        env:
-        - name: FRONTEND_ADDR
-          value: "frontend:80"
-      containers:
-      - name: main
-        securityContext:
-          allowPrivilegeEscalation: false
-          capabilities:
-            drop:
-              - all
-          privileged: false
-          readOnlyRootFilesystem: true
-        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.3.9
-        env:
-        - name: FRONTEND_ADDR
-          value: "frontend:80"
-        - name: USERS
-          value: "10"
-        resources:
-          requests:
-            cpu: 300m
-            memory: 256Mi
-          limits:
-            cpu: 500m
-            memory: 512Mi
+
+#Load Generator locust
+#---
+#apiVersion: apps/v1
+#kind: Deployment
+#metadata:
+#  name: loadgenerator
+#spec:
+#  selector:
+#    matchLabels:
+#      app: loadgenerator
+#  replicas: 1
+#  template:
+#    metadata:
+#      labels:
+#        app: loadgenerator
+#      annotations:
+#        sidecar.istio.io/rewriteAppHTTPProbers: "true"
+#    spec:
+#      serviceAccountName: default
+#      terminationGracePeriodSeconds: 5
+#      restartPolicy: Always
+#      securityContext:
+#        fsGroup: 1000
+#        runAsGroup: 1000
+#        runAsNonRoot: true
+#        runAsUser: 1000
+#      initContainers:
+#      - command:
+#        - /bin/sh
+#        - -exc
+#        - |
+#          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+#          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+#          if test $STATUSCODE -ne 200; then
+#              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+#              exit 1
+#          fi
+#        name: frontend-check
+#        image: busybox:latest
+#        env:
+#        - name: FRONTEND_ADDR
+#          value: "frontend:80"
+#      containers:
+#      - name: main
+#        securityContext:
+#          allowPrivilegeEscalation: false
+#          capabilities:
+#            drop:
+#              - all
+#          privileged: false
+#          readOnlyRootFilesystem: true
+#        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.3.9
+#        env:
+#        - name: FRONTEND_ADDR
+#          value: "frontend:80"
+#        - name: USERS
+#          value: "10"
+#        resources:
+#          requests:
+#            cpu: 300m
+#            memory: 256Mi
+#          limits:
+#            cpu: 500m
+#            memory: 512Mi
 ---
 apiVersion: apps/v1
 kind: Deployment
@@ -654,11 +660,13 @@ spec:
         - name: PORT
           value: "7000"
         - name: DISABLE_TRACING
-          value: "1"
+          value: "0"
         - name: DISABLE_PROFILER
           value: "1"
         - name: DISABLE_DEBUGGER
           value: "1"
+        - name: JAEGER_SERVICE_ADDR
+          value: "jaeger-collector:14268"
         readinessProbe:
           exec:
             command: ["/bin/grpc_health_probe", "-addr=:7000"]
@@ -723,11 +731,11 @@ spec:
         - name: DISABLE_STATS
           value: "1"
         - name: DISABLE_TRACING
-          value: "1"
+          value: "0"
         - name: DISABLE_PROFILER
           value: "1"
-        # - name: JAEGER_SERVICE_ADDR
-        #   value: "jaeger-collector:14268"
+        - name: JAEGER_SERVICE_ADDR
+          value: "jaeger-collector:14268"
         readinessProbe:
           periodSeconds: 5
           exec:
@@ -859,9 +867,9 @@ spec:
         - name: DISABLE_STATS
           value: "1"
         - name: DISABLE_TRACING
-          value: "1"
-        # - name: JAEGER_SERVICE_ADDR
-        #   value: "jaeger-collector:14268"
+          value: "0"
+        - name: JAEGER_SERVICE_ADDR
+          value: "jaeger-collector:14268"
         resources:
           requests:
             cpu: 200m
